smart-on-fhir/smart-on-fhir.github.io

- tutorials/authorization/index.md
The current How-To link returns a 404. This updates the link to point to http://docs.smartplatforms.org/sandbox/register/
> Fix link to How-To link

- authorization/index.md
Refs:  RFC6749 (10.3, 10.4, 10.5, 10.13, 10.14); RFC6750 (5.3); RFC6819 (4.1.2, 4.4.1.9); OIDC16.4 (16.5)
Risk Assessment Rows:  4, 5, 10, 12, 14 
Description:  Apps need to protect themselves from malicious apps running on the same platform, counterfeit authorization servers, and counterfeit resource servers.  
Recommendation:  Although protections are integrated throughout the profiles (e.g., in parameters), having these key protections in a separate section will help app developers understand their importance and collective value.
> App self-protection

- authorization/index.md
Changed this to step 1 of the authorization-and-retrieval sequence.
Most of these changes were motivated by the risk assessment.
1)  Made `state` a "required" parameter (instead of "recommended").
Ref:  RFC6749 (10.12)
Risk Assessment Row:  10
2) Require that client validate state parameter
Ref:  RFC6749 (10.14)
Risk Assessment Row:  12
3) High entropy for state parameter
Ref: RFC6819 (4.3.5) + MITRE recommendation
Risk Assessment Row:  23
4) Added "audience" (`aud`) parameter as countermeasure for counterfeit resource server
Ref: RFC6819 (4.6.4)
Risk Assessment Row:  33
5) Added OPTION for app to sign request 
Ref:  OIDC (16.1)
Risk Assessment Row:  37
6) Incorporated OpenID into description and example
Ref:  OIDC (16.1, 16.2)
Risk Assessment Row:  37, 38
> Changes to request for authorization

- authorization/index.md
(editorial)
Since the launch sequence is assumed to have occurred before the authorization process begins, I created a separate section for describing the two types of launch sequence -- EHR and standalone.  Also, added explanation of how the standalone launch ultimately obtains context.
> Revision of Launch Sequences section

- authorization/index.md
The new content re app protection was misplaced, so I moved it to precede step 1.
Also, the old step 1 (App asks for authorization) was still there, so I deleted it.
However, step 2 (EHR evaluates authorization request) seems to have disappeared.  I thought I had submitted changes for that section, but I don't see them in any of the patches.  Unless you have an explanation that I'm not seeing, I'll just copy it from the master, make the changes, and submit them.
> Editing corrections

- authorization/index.md
1) Presentation of bearer token
Ref:  RFC6819 (4.6.1, 4.6.2, 4.6.4, 4.6.5, 4.6.6, 4.6.7) 
Risk Assessment Row:  30, 31, 33, 34, 35, 36
Add exchange of bearer token with resource server, with token presented in authorization header.
2) RS token validation 
Ref:  RFC6819 (4.6.5)
Risk Assessment Rows:  34
Change:  Add resource server validation of bearer token and checking that "aud" parameter is its own URL.
3) App warning re reference to resource on different RS
Ref:  RFC6819 (4.6.6)
Risk Assessment Row:  35
Change:  Added warning for app to reject any reference it may receive pointing to a FHIR resource on a different resource server.
> Exchange with RS

- authorization/index.md
1) Ref:  RFC6819 (4.6.6, 4.6.7)
Risk Assessment Row:  35, 36
Change:  Lock down the access token type to "Bearer."  
2) Ref:  OIDC (16.4, 16.5, 16.9); RFC6749 (10.4); MITRE OAuth Profile (4.2.1.5)
Risk Assessment Row:  5, 41, 43
Change:  Added the following access token parameters:  host, client_id, username, timestamp.  Client_id is required for confidential clients only.  Username is optional.  
3) Ref:  RFC6749 (10.4); RFC6819 (4.1.2, 4.6.1); OIDC (16.4, 16.5)
Risk Assessment Rows:  5, 13, 14, 15, 30
Change:  Added explanation of refresh tokens, and advice for assigning establishing "expires_in" values for access and refresh tokens, and for confidential and public clients.
4) Ref:  MITRE OAuth Profile (4.2.1.5)
Risk Assessment Rows:  44
Change:  Added option for the authorization …
> Mods to app exchanges code for token

- authorization/index.md
I've revised the descriptions for both EHR and Standalone launches, adding new sequence diagrams to each.  
As part of this, I moved some of the detail that previously had been in the overview down into the descriptions.
Some of the text relating to conformance statements seemed inconsistent and didn't align with the sequence diagrams.  I've tried to clean that up.
> Revised Launch descriptions

- authorization/index.md
Previously I pulled the detail re EHR launch and stand-alone launch out of the overview and moved them into the launch descriptions.  But I neglected to delete the moved content from the overview.  This change does that.
Also, we're replacing the single, complex sequence diagrams with 4 separate sequences.  So I have deleted it from the overview.
> Removed detail and sequence diagram from overview

- authorization/index.md
1) Added "App runs on a trusted server" to confidential app attributes.  
Justification:  Specified execution environment for public apps, but not confidential.  Adding this bullet made attributes parallel. 
2) Deleted bullet 1, and added Android to public app attributes.  
Justification:  Bullet 1 implied that public apps always launch from an EHR.  Launch context is orthogonal to whether the app is public or confidential.  Also, adding android clarifies that mobile apps are included.
> Confidential/Public App attributes

- authorization/index.md
Issue:  Table said "state" parameter was "required," but in text said it "SHOULD" be used.
Change:  Changed SHOULD to MUST, to be consistent with "required."
> State parameter

- authorization/backend-services/index.md
- https://jwt.io > http://jwt.io (Github Pages doesn't offer https hosting)
- Use example.com for the 'bilirubin result monitoring' example issuer URL
- Fix SMART Health IT URL
> [minor] Fix documentation links

- authorization/scopes-and-launch-context/index.md
Added scope parameters to enable an app to request that a refresh token be issued along with the access token.  
1) Changed the "most often used" parameter from offline_access to online_access, since offline_access should be the exceptional case, not the most often used.
2) Added a table defining both online_access and offline_access parameters.
> App requests for refresh token

- argonaut/index.md
Updated link to point to the Argonaut authz profile instead of the old SMART on FHIR profiles.  
Modified wording of use case explanations.
> Updated link and content

- authorization/index.md
RFC 6749 includes this requirement w.r.t the Authz Server's response containing the bearer token.  As protection against access token leakage, we include advice to clients not to cache access tokens.  This should provide additional protection.
> Added no-cache protection

- specification/index.md
Revised definitions per Argonaut use case definitions, which allow for much broader applicability of this profile, and avoid dictating system architecture, enabling, for example, an authorization server, FHIR resource server, and EHR app to be operated by different entities.  Also, "ownership" is a very contentious concept whose legal definition varies among states, and whose local definition also varies -- need to avoid using it.
> Definitions

- specification/index.md
Incorporated language to clarify that the OS "default browser" a client uses should be configured i.a.w. institutional policy.
Also added ref to para 6.1 of OAuth 2.0 for Native Apps Draft, which describes the associated risk.
> Revision to 2.1.2 re OS default browser

- authorization/index.md
Add missing % in raw tag of section 4, which was causing {{access_token}} not to be displayed.
> Add missing % in section 4

- authorization/index.md
Updated section 3 to clarify that the format of the bearer access token is up to the organization.  Aligned the wording with wording in EHR-to-EHR profile.
> Revised section 3 to remove JWT token

- authorization/index.md
We've had a lot of confusion about the client_id in the token request. The OAuth 2 spec states that it is [required if the app is a public application](http://tools.ietf.org/html/rfc6749#section-4.1.3), but the current SMART doc states it's optional, without qualification.
I'm not sure I'm completely satisfied with the changes - do we have an "optionally required" flag or some other way to call out that this is required for some use cases?
> Correct token request doc for public clients

- authorization/scopes-and-launch-context/index.md
Both offline_access and online_access can be used "after the access token expires."  The difference is that offline_access can be used to refresh an expired token even after the end-user no longer is online.
> offline_access clarification

- authorization/best-practices/index.md
1)  Corrected some typos.
2)  Deleted "(but note that requiring client authentication via mutual TLS may limit
interoperability of the client across server environments)."  I have several concerns about this phrase.  First, it tends to imply that a policy that requires a client to authenticate itself is bad policy -- which isn't necessarily the case, and who are we to tell organizations what their policy should be?  Second, maximizing the interoperability of a client is not the responsibility of an authorization server, or the organization holding the resource.  Third (related to 2), just because one authorization server requires a client to authenticate itself doesn't mean that every authorization server needs to do so.  
3) Deleted the question re 2.1.2, with my response --  I don’t …
> Typo corrections and comments

- authorization/best-practices/index.md
Added 2.5.2, describing the need for an AS to include in an access token the intended recipient(s) of that token.
> Token redirect/phishing

- tutorials/index.md
There was a space character ' ' between the link's label and the url placeholder - resulting in a broken link.
> Remove broken link for tutorials/testing

- authorization/scopes-and-launch-context/index.md
Previously, wildcard scopes were ambiguous. They could be either interpreted in different ways:
- A client convenience to request all previously granted (out-of-band) scopes with a simple, single scope
- A client's request for access to all FHIR resources available _now_
- A client's request for access to all FHIR resources available now _and in the future_
With the introduction of use cases like offline access and Sync for Science, it is important to clearly and explicitly define the expectations around wildcard scopes so that FHIR/authorization server implementers and client developers have the same understanding.
> Explicitly define expectations and the meaning behind wildcard scopes.

- authorization/backend-services/index.md
the external reference was misleading as it didn't define any valid/relevant scopes. This change formally defines the system scopes, and clarifies the documentation around that. A later pull request will deal with communication request (it's wrong to mandate that all uses of the backend services involve systems that have clinical users)
> clarify about scopes
